---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:

    # - name: test_db
    #   mysql_db:
    #     login_user=root
    #     login_password=password
    #     login_host=B_address
    #     login_port=B_port
    #     name=B_database
    #     state=present
    #   when: dbstatus.rc == 0
    #   no_log: yes # You can disable this, if you want to print the stdout

    - name: Install prerequisites
      apt:
        pkg:
          - aptitude
        update_cache: yes
        state: latest
        force_apt_get: yes

    - name: Install Apache
      apt:
        pkg:
          - apache2
          - php7.4-cli
        update_cache: yes
        state: latest

    - name: Create repo folder
      file:
        path: "/opt/repository"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Clone backend build
      become_user: "{{ app_user }}"
      git:
        repo: '{{ be_repo }}'
        dest: '/opt/repository/backend/{{ date }}'
        # key_file: /home/anss/.ssh/id_ed25519

    - name: Build laravel
      shell:
        chdir: '/opt/repository/backend/{{ date }}'
        cmd: ./a.sh

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Create document BE root
      file:
        dest: "/var/www/{{ http_host }}"
        src: '/opt/repository/backend/{{ date }}'
        state: link
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Copy index test page
      template:
        src: "files/index.html"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
